services:
  web:
    build: .
    container_name: tst-leaderboard
    ports:
      - "3000:80"
    environment:
      - VITE_REACT_API_BASE_URL=/api
      - VITE_REACT_API_SCORE_URL=/api/get-leaderboard
      - VITE_REACT_API_WEBSOCKET_URL=ws://tst-api-api-1:8000/ws  
    networks:
      - tst-network
    command: sh -c "sleep 5 && nginx -g 'daemon off;'"  

networks:
  tst-network:
    external: true